### ISSUE TITLE
Configuration file resets every time the game loads

### ISSUE THREAD

**Issue by genderneutralnoun** [gabriella-campos-davis/Herbarium#10]
Title, essentially. I've tested this on Herbarium 1.2.0 on VS 1.19.8 with no other mods than Herbarium and the three Wildcraft modules. The game reads the configuration values as it loads, so things such as disabling plant damage works, but somewhere in the startup process after that (I assume anyway) it resets the HerbariumConfig.json to completely default values. Which means that I have to edit the config to my preferred values every single time I load up the mod. It's extremely annoying. Sorry if I seem a bit short, but the issue has been reported on both the VS Discord and the actual comments of the Herbarium mod, with no apparent acknowledgment... hence I thought I would create an issue here to bring attention to it. Thank you for the great mod, and thank you in advance for hopefully fixing this issue.

**Comment by gabriella-campos-davis** [comment]
Hey thank you for the bug report, this should be fixed in the latest 1.3.0 version of Herbarium :)
