### ISSUE TITLE
Herbs module BETransient error

### ISSUE THREAD

**Issue by RogueRaiden** [gabriella-campos-davis/Herbarium#9]
17.5.2024 06:47:24 [Server Error] BETransient @507227, 167, 521321: cannot find block attributes for wildcraftherb:seedling-lavender-planted. Will stop transient timer

**Comment by gabriella-campos-davis** [comment]
Does this just show up in the server logs just once or multiple times? and also has there been any noticeable issues associated with it?

**Comment by RogueRaiden** [comment]
a few times... im not sure about issues
![image](https://github.com/gabriella-campos-davis/Herbarium/assets/26943867/ed48f9e6-cab5-457c-91fe-1f65745a5a6d)

**Comment by gabriella-campos-davis** [comment]
would it be possible to find if there's a lavender plant at the coordinates? also you said it stopped after a server restart? so it's not throwing the error anymore?

**Comment by gabriella-campos-davis** [comment]
Glad it resolved itself, let me know if there's further issues
